In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## Define the vocabulary size
voc_size=10000

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[8063, 5177, 3338, 6749],
 [8063, 5177, 3338, 8731],
 [8063, 8850, 3338, 4410],
 [2260, 3070, 3281, 5140, 3378],
 [2260, 3070, 3281, 5140, 7851],
 [1655, 8063, 8492, 3338, 2290],
 [2124, 8097, 701, 5140]]

In [8]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8063 5177 3338 6749]
 [   0    0    0    0 8063 5177 3338 8731]
 [   0    0    0    0 8063 8850 3338 4410]
 [   0    0    0 2260 3070 3281 5140 3378]
 [   0    0    0 2260 3070 3281 5140 7851]
 [   0    0    0 1655 8063 8492 3338 2290]
 [   0    0    0    0 2124 8097  701 5140]]


In [11]:
## feature representation
dim=10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

2025-05-19 13:04:34.293167: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:274] failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error


In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [14]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 65ms/step


array([[[ 0.02256313,  0.01872209, -0.00450557,  0.0205485 ,
         -0.00693689,  0.02324798,  0.02188158,  0.02973035,
         -0.0047429 , -0.01817467],
        [ 0.02256313,  0.01872209, -0.00450557,  0.0205485 ,
         -0.00693689,  0.02324798,  0.02188158,  0.02973035,
         -0.0047429 , -0.01817467],
        [ 0.02256313,  0.01872209, -0.00450557,  0.0205485 ,
         -0.00693689,  0.02324798,  0.02188158,  0.02973035,
         -0.0047429 , -0.01817467],
        [ 0.02256313,  0.01872209, -0.00450557,  0.0205485 ,
         -0.00693689,  0.02324798,  0.02188158,  0.02973035,
         -0.0047429 , -0.01817467],
        [ 0.03322219,  0.03294488, -0.00117321, -0.00689951,
         -0.04736122,  0.03188062, -0.03803974, -0.00664522,
          0.02757312,  0.04696479],
        [-0.01246782, -0.04214209,  0.00068536,  0.03546072,
         -0.03187932, -0.01804713, -0.03690217,  0.04618299,
         -0.03052471, -0.03118963],
        [ 0.02509208,  0.01028723, -0.00016386, -0.0

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 8063, 5177, 3338, 6749], dtype=int32)

In [16]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 90ms/step


array([[ 0.02256313,  0.01872209, -0.00450557,  0.0205485 , -0.00693689,
         0.02324798,  0.02188158,  0.02973035, -0.0047429 , -0.01817467],
       [ 0.02256313,  0.01872209, -0.00450557,  0.0205485 , -0.00693689,
         0.02324798,  0.02188158,  0.02973035, -0.0047429 , -0.01817467],
       [ 0.02256313,  0.01872209, -0.00450557,  0.0205485 , -0.00693689,
         0.02324798,  0.02188158,  0.02973035, -0.0047429 , -0.01817467],
       [ 0.02256313,  0.01872209, -0.00450557,  0.0205485 , -0.00693689,
         0.02324798,  0.02188158,  0.02973035, -0.0047429 , -0.01817467],
       [ 0.03322219,  0.03294488, -0.00117321, -0.00689951, -0.04736122,
         0.03188062, -0.03803974, -0.00664522,  0.02757312,  0.04696479],
       [-0.01246782, -0.04214209,  0.00068536,  0.03546072, -0.03187932,
        -0.01804713, -0.03690217,  0.04618299, -0.03052471, -0.03118963],
       [ 0.02509208,  0.01028723, -0.00016386, -0.00829545,  0.0397842 ,
         0.04265119,  0.00192971,  0.00879744